config/routes.rb
Agalma::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
     resources :institucions 
     get 'institucions', to: 'institucions#index'
     root "institucions#index"	

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/institucion.rb
class Institucion < ActiveRecord::Base
    validates :name, 	presence: true,
						length: { minimum: 4 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/institucions_controller.rb
class InstitucionsController < ApplicationController
	def new
		@institucion = Institucion.new
	end	

	def show
		@institucion = Institucion.find(params[:id])
	end

	def index
		@institucions = Institucion.all
	end	

	def create
  		@institucion = Institucion.new(params[:institucion].permit(:name, :direction))
 		#@institucion.user_id = current_user.id
  		if @institucion.save
    		redirect_to @institucion
  		else
    		render 'new'
  		end
	end

	def edit
  		@institucion = Institucion.find(params[:id])
	end

	def update
  		@institucion = Institucion.find(params[:id])
 
  		if @institucion.update(institucion_params)
    		redirect_to @institucion
  		else
    		render 'edit'
  		end
	end

	def destroy
		@institucion = Institucion.find(params[:id])
		@institucion.destroy

		redirect_to institucions_path
	end
	private
		def institucion_params
			params.require(:institucion).permit(:name, :direction)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/institucions_helper.rb
module InstitucionsHelper
end

app/views/institucions/_form.html.erb
<%= form_for @institucion do |f| %>
  <% if @institucion.errors.any?%>
  <div id="errorExplanation">
    <h2><%= pluralize(@institucion.errors.count, "error") %> No se pudo guardar por:</h2>
    <ul><% @institucion.errors.full_messages.each do |msg| %><li><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>
  <p>
    <%= f.label 'Nombre' %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label 'Direccion' %><br>
    <%= f.text_field :direction %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/institucions/edit.html.erb
<h1>Editar institucion</h1>
 
<%= render 'form' %>

<%= link_to 'Atras', institucions_path %>
<%= link_to 'Eliminar', institucion_path(@institucion),
                    method: :delete, data: { confirm:'Estas seguro?' } %>

app/views/institucions/index.html.erb
<h1>Nuestras Sucursales!</h1>
<% if !@institucions.empty? %> 
<table>
  <tr>
    <th>Nombre</th>
    <th>Direccion</th>
  </tr>
  <% @institucions.each do |institucion| %>
    <tr>
      <td><%= link_to institucion.name, institucion_path(institucion) %></td> 
      <td><%= institucion.direction %></td>
      <td><%= link_to 'Editar', edit_institucion_path(institucion) %></td>
      <td><%= link_to 'Eliminar', institucion_path(institucion),
                    method: :delete, data: { confirm:'Estas seguro?' } %></td>
    </tr>
  <% end %> 
</table>
<% else %>
<h2> Puede comenzar a cargar sucursales ahora. </h2>
<% end %>
<%= link_to 'Nueva Sucursal', new_institucion_path %>

app/views/institucions/new.html.erb
<h1>Nueva Sucursal!</h1>

<%= render 'form' %>

<%= link_to 'Atras', institucions_path %>

app/views/institucions/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @institucion.name %>
</p>
 
<p>
  <strong>Direccion:</strong>
  <%= @institucion.direction %>
</p>
  
<%= link_to 'Atras', institucions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agalma</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='container'>
    <div id='user_nav'>
      <% if user_signed_in? %>
	 Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sing up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
<%= yield %>
  </div>
 </body>
</html>